# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-08 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='typeid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='goods',
            name='dealerid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='categoryid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='childcid1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='childcid2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='childcid3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='marketprice1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='marketprice2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='marketprice3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='price1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='price2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='price3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='productid1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='productid2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='productid3',
            field=models.CharField(max_length=20),
        ),
    ]
